// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c34293775dc2ff87dcea7747e974cd1b9ab4f52d/clipboard-js/clipboard-js.d.ts
declare namespace clipboard {

    interface IClipboardJsStatic {
        copy(val: string | Element): Promise<void>;
        paste(): Promise<string>;
    }
}

declare var clipboard: clipboard.IClipboardJsStatic;

declare module 'clipboard-js' {
    export = clipboard;
}
